$(document).ready(function() {
    let images = [
        { 
            src: "images/ice.jpg", 
            caption: "I - for Ice", 
            aiPrompt: "An image of Ice"
        },
        { 
            src: "images/banana.jpg", 
            caption: "B - for Banana", 
            aiPrompt: "A random banana"
        },
        { 
            src: "images/apple.jpg", 
            caption: "A - for Apple", 
            aiPrompt: "A Apple Fuit"
        },
        { 
            src: "images/dolphin.jpg", 
            caption: "D - for Dolphin", 
            aiPrompt: "A high-quality image of a Dolphin"
        },
        { 
            src: "images/sunflower.jpg", 
            caption: "S - for Sunflower", 
            aiPrompt: "A beautiful image of a Sunflower"
        },
        { 
            src: "images/helicopter.jpg", 
            caption: "H - for Helicopter", 
            aiPrompt: "A image of a Helicopter"
        },
        { 
            src: "images/elephant.jpg", 
            caption: "E - for Elephant", 
            aiPrompt: "Elephant in nature"
        },
        { 
            src: "images/icecream.jpg", 
            caption: "I - for Ice Cream", 
            aiPrompt: "A high-quality image of Ice Cream"
        },
        { 
            src: "images/kangroo.jpg", 
            caption: "K - for Kangaroo", 
            aiPrompt: "big Kangroo"
        },
        { 
            src: "images/house.jpg", 
            caption: "H - for House", 
            aiPrompt: "A image of a House"
        }
    ];

    let currentIndex = 0;

    function loadSlide(index) {
        // Fade out current image and load the new one
        $("#slide-img").fadeOut(400, function() {
            $(this).attr("src", images[index].src)
                   .attr("alt", images[index].caption)
                   .fadeIn(400);
            $("#caption").text(images[index].caption);
            $("#ai-caption").text("Generated by AI: \"" + images[index].aiPrompt + "\"");
        });

        currentIndex = index;
    }

    // Navigation click handler
    $("#image-nav a").click(function(e) {
        e.preventDefault();
        let index = $(this).data("index");
        loadSlide(index);
    });

    // Load the first image initially
    loadSlide(currentIndex);
});
